project_id = "kvzylywteqjqqpxsplfp"

[functions.chat]
verify_jwt = false

[functions.generate-image]
verify_jwt = false

[functions.analyze]
verify_jwt = false

[functions.web-search]
verify_jwt = false

[functions.edit-image]
verify_jwt = false
