// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kvzylywteqjqqpxsplfp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imt2enlseXd0ZXFqcXFweHNwbGZwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzYzOTI0NzYsImV4cCI6MjA5MTk2ODQ3Nn0.DX9LOBmfzvMrJcd_z3BljUhzq8hq_WlhacKdm8HPiT4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});